# Generated by Django 3.2.3 on 2021-05-13 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Property Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Property Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Property Name')),
                ('rent_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Property rent price')),
                ('primary_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Property price')),
                ('bedrooms', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('property_size', models.CharField(max_length=50)),
                ('furnished', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('localtion', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_featured', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('property_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.category', verbose_name='Property Category')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertytype', verbose_name='Property Type')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
