# Generated by Django 3.2.3 on 2021-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='primary_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Property rent price'),
        ),
    ]
